### ISSUE TITLE
It's impossible to zoom in on items on the right or bottom of the diagram.

### ISSUE THREAD

**Issue by meetinthemiddle-be** [mike-goodwin/owasp-threat-dragon-core#72]
The zoom "+" and "-" buttons scale the diagram with the top left corner as an anchor point, so zooming in pushes items on right and bottom out of the viewport. For bigger diagrams, this may become a usability issue.

Proposals for improvement:

Preferred : Add a "hand" icon that allows you to drag the view to add pan functionality (most intuitive)

Alternatively : When an element is selected, use a point on the selected element to serve as anchor point for the zoom operation instead of the top-left corner.

**Comment by jgadsden** [comment]
On zoom the scrollbars do not update to follow the changing view scope. Hence zooming in means that some of the diagram is inaccessible

**Comment by jgadsden** [comment]
Hello @meetinthemiddle-be
This issue is part of a larger problem with the zoom feature, as is the issue #73 . We are removing zoom feature temproarily in #94 and will reinstate it when zoom is working fully, tracked by issue #95 . Thanks for raising both these issues, and I hope it is OK to close your issue as it is now part of #95
